### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by Craig5117** [Craig5117/slp-goalden#1]
Models:
User: (has many Student, has many goals)
	id
        email 
        username
        password (bcrypt)
Student: (belongs to User, has many student_goal)
	id
	student_name
	user_id
Goal: (belongs to user, belongs to student_goal)
	id
	goal_name
	description
	user_id
Student_goal: (belongs to student, has many trial)
	id
	student_id
	goal_id
Trial: (belongs to student_goal)
	id
	date
	successful
	percent
	student_goal_id

**Comment by Craig5117** [comment]
This is the updated list. I think it is organized properly now. It is possible I missed a relationship. The reason for the extra table is that it would become cumbersome to add extra blank columns to student in order to track what goals a student has, it would also be bulky in the goals table to duplicate the goal name and description each time another student has the same goal. This should be the most efficient way to organize it.

**Comment by fancibleunicorn** [comment]
set up all models and pushed to develop
